import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster"
import { Blaka, Righteous, Open_Sans } from 'next/font/google';
import "./globals.css";

const blaka = Blaka({
  weight: ['400'], // Specify font weights (optional)
  subsets: ['latin'], // Specify subsets
  variable: "--font-quicksand",
});

const openSans = Open_Sans({
  weight: ['400'], // Specify font weights (optional)
  subsets: ['latin'], // Specify subsets
  variable: "--font-open-sans",
});

const righteous = Righteous({
  weight: ['400'], // Specify font weights (optional)
  subsets: ['latin'], // Specify subsets
  variable: "--font-righteous",
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${blaka.variable} ${righteous.variable} ${openSans.variable}`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
